import React from 'react';

const Footer = () => {
  const currentYear = new Date().getFullYear();

  return (
    <footer className="bg-gray-800 text-white py-8 px-4 mt-12">
      <div className="container mx-auto max-w-4xl">
        
        {/* Disclaimer Section */}
        <div className="mb-6">
          <h3 className="text-lg font-semibold mb-3 text-center text-gray-400">⚠️ Important Disclaimer</h3>
          <div className="bg-gray-700 p-4 rounded-lg text-sm leading-relaxed">
            <p className="mb-3">
              <strong>Recommendations Only:</strong> This resume analysis tool provides suggestions and recommendations only. 
              All feedback is generated by automated algorithms and should be considered as guidance rather than definitive advice.
            </p>
            <p className="mb-3">
              <strong>No Guarantee of Accuracy:</strong> While we strive for accuracy, inaccuracies may occur in the analysis. 
              We recommend using this tool as one of many resources in your job search and resume improvement process.
            </p>
            <p className="mb-3">
              <strong>Industry Focus:</strong> Some analysis features and keyword matching are specifically tailoured 
              towards civil engineering and related technical fields. Results may be less relevant for other industries.
            </p>
            <p>
              <strong>Professional Review:</strong> For important applications, we recommend having your resume 
              reviewed by a professional career adviser or industry expert.
            </p>
          </div>
        </div>

        {/* Divider */}
        <div className="border-t border-gray-600 my-6"></div>

         {/* Social Media Links */}
         <div className="text-center mb-8">
          <h3 className="text-lg font-semibold mb-4 text-gray-400">🔗 Connect with me</h3>
          <div className="flex justify-center gap-4">
            <a
              href="https://linkedin.com/in/lachlanho"
              target="_blank"
              rel="noopener noreferrer"
              className="flex items-center gap-2 px-3 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700 transition-colours"
            >
              <svg className="w-4 h-4" fill="currentColor" viewBox="0 0 24 24">
                <path d="M20.447 20.452h-3.554v-5.569c0-1.328-.027-3.037-1.852-3.037-1.853 0-2.136 1.445-2.136 2.939v5.667H9.351V9h3.414v1.561h.046c.477-.9 1.637-1.85 3.37-1.85 3.601 0 4.267 2.37 4.267 5.455v6.286zM5.337 7.433c-1.144 0-2.063-.926-2.063-2.065 0-1.138.92-2.063 2.063-2.063 1.14 0 2.064.925 2.064 2.063 0 1.139-.925 2.065-2.064 2.065zm1.782 13.019H3.555V9h3.564v11.452zM22.225 0H1.771C.792 0 0 .774 0 1.729v20.542C0 23.227.792 24 1.771 24h20.451C23.2 24 24 23.227 24 22.271V1.729C24 .774 23.2 0 22.222 0h.003z"/>
              </svg>
              LinkedIn
            </a>
            
            <a
              href="mailto:lachlan.ho@gmail.com"
              className="flex items-center gap-2 px-3 py-2 bg-gray-600 text-white rounded-lg hover:bg-gray-700 transition-colours"
            >
              <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M3 8l7.89 7.89c.39.39 1.02.39 1.41 0L21 8M5 19h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v10a2 2 0 002 2z" />
              </svg>
              Email
            </a>
            
            <a
              href="https://github.com/lachho"
              target="_blank"
              rel="noopener noreferrer"
              className="flex items-center gap-2 px-3 py-2 bg-gray-900 text-white rounded-lg hover:bg-black transition-colours"
            >
              <svg className="w-4 h-4" fill="currentColor" viewBox="0 0 24 24">
                <path d="M12 0c-6.626 0-12 5.373-12 12 0 5.302 3.438 9.8 8.207 11.387.599.111.793-.261.793-.577v-2.234c-3.338.726-4.033-1.416-4.033-1.416-.546-1.387-1.333-1.756-1.333-1.756-1.089-.745.083-.729.083-.729 1.205.084 1.839 1.237 1.839 1.237 1.07 1.834 2.807 1.304 3.492.997.107-.775.418-1.305.762-1.604-2.665-.305-5.467-1.334-5.467-5.931 0-1.311.469-2.381 1.236-3.221-.124-.303-.535-1.524.117-3.176 0 0 1.008-.322 3.301 1.23.957-.266 1.983-.399 3.003-.404 1.02.005 2.047.138 3.006.404 2.291-1.552 3.297-1.23 3.297-1.23.653 1.653.242 2.874.118 3.176.77.84 1.235 1.911 1.235 3.221 0 4.609-2.807 5.624-5.479 5.921.43.372.823 1.102.823 2.222v3.293c0 .319.192.694.801.576 4.765-1.589 8.199-6.086 8.199-11.386 0-6.627-5.373-12-12-12z"/>
              </svg>
              GitHub
            </a>
          </div>
        </div>
        {/* Divider */}
        <div className="border-t border-gray-600 my-6"></div>

        {/* Copyright and Links */}
        <div className="flex flex-col md:flex-row justify-between items-center text-sm text-gray-400">
          <div className="mb-4 md:mb-0">
            <p>&copy; {currentYear} Lachlan Ho. All rights reserved.</p>
          </div>
          
          <div className="flex space-x-6">
            <span className="hover:text-white transition-colours cursor-pointer">Privacy Policy</span>
            <span className="hover:text-white transition-colours cursor-pointer">Terms of Service</span>
            <span className="hover:text-white transition-colours cursor-pointer">Contact</span>
          </div>
        </div>
      </div>

      
    </footer>
  );
};
       

export default Footer; 